export const EXTENTSION_NAME = 'Qubership APIHUB';
export const ENVIRONMENT_SECTION = 'APIHUB Environment';
export const DOCUMENTS_SECTION = 'Documents to Publish';
export const PUBLISH_SECTION = 'Publish to APIHUB';
export const TEST_PAT_TOKEN = 'token';
export const TEST_BROKEN_PAT_TOKEN = 'broken_token';
export const LOCAL_SERVER_URL = 'http://localhost:';
export const LOCAL_SERVER_PORT = 3000;
export const LOCAL_SERVER_FULL_URL = `${LOCAL_SERVER_URL}${LOCAL_SERVER_PORT}`;
