openapi: 3.0.3
info:
  title: Pets
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io\
  - name: user
    description: Operations about user
paths:
  /pet:
    $ref: 'Pet/Operations/updatePet.yaml'
  /pet/findByStatus:
    $ref: 'Pet/Operations/findPetsByStatus.yaml'
  /pet/findByTags:
    $ref: 'Pet/Operations/findPetsByTags.yaml'
  /pet/{petId}:
    $ref: 'Pet/Operations/getPetById.yaml'
  /pet/{petId}/uploadImage:
    $ref: 'Pet/Operations/uploadFile.yaml'
  /store/inventory:
    $ref: 'Store/Operations/getInventory.yaml'
  /store/order:
    $ref: 'Store/Operations/placeOrder.yaml'
  /store/order/{orderId}:
    $ref: 'Store/Operations/getOrderById.yaml'
  /user:
    $ref: 'User/Operations/createUser.yaml'
  /user/createWithList:
    $ref: 'User/Operations/createUsersWithListInput.yaml'
  /user/login:
    $ref: 'User/Operations/loginUser.yaml'
  /user/logout:
    $ref: 'User/Operations/logoutUser.yaml'
  /user/{username}:
    $ref: 'User/Operations/getUserByName.yaml'
components:
  schemas:
    Pet: 
      $ref: 'Pet/Models/Pet.yaml'
    Category:
      $ref: 'Pet/Models/Category.yaml'
    User:
      $ref: 'User/Models/User.yaml'
    Tag:
      $ref: 'Pet/Models/Tag.yaml'
    ApiResponse:
      $ref: 'Pet/Models/ApiResponse.yaml'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header